### ISSUE TITLE
Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by nitinmukesh** [xyfJASON/ctrlora#6]
How to fix this issue

```
(venv) C:\aitools\ctrlora>python app/gradio_ctrlora.py
logging improved.
Running on local URL:  http://0.0.0.0:7860
IMPORTANT: You are using gradio version 4.27.0, however version 5.0.1 is available, please upgrade.
--------

To create a public link, set `share=True` in `launch()`.
Loading config...
No module 'xformers'. Proceeding without it.
ControlInferenceLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: 100%|█████████████████████████████████████████████████████████████████| 939k/939k [00:00<00:00, 1.14MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 512k/512k [00:00<00:00, 782kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████| 389/389 [00:00<?, ?B/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████| 905/905 [00:00<00:00, 909kB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████| 4.41k/4.41k [00:00<?, ?B/s]
Downloading: 100%|███████████████████████████████████████████████████████████████| 1.59G/1.59G [02:11<00:00, 13.0MB/s]
Loaded model config from [./configs\inference/ctrlora_sd15_rank128_1lora.yaml]
Config loaded
Loading checkpoints
Loaded state_dict from [./ckpts\sd15\v1-5-pruned.ckpt]
Loaded state_dict from [./ckpts\ctrlora-basecn\ctrlora_sd15_basecn700k.ckpt]
Loaded state_dict from [./ckpts\ctrlora-loras\base-conditions\ctrlora_sd15_basecn700k_canny_rank128.ckpt]
Checkpoints loaded
Prompt is: masterpiece, best quality, A beautiful girl in jungle
Negative Prompt is: worst quality, low quality, NSFW
Global seed set to 12345
Data shape for DDIM sampling is (1, 4, 75, 100), eta 0
Running DDIM Sampling with 20 timesteps
DDIM Sampler:   0%|                                                                            | 0/20 [00:09<?, ?it/s]
Traceback (most recent call last):
  File "C:\aitools\ctrlora\venv\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "C:\aitools\ctrlora\venv\lib\site-packages\gradio\route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\aitools\ctrlora\venv\lib\site-packages\gradio\blocks.py", line 1788, in process_api
    result = await self.call_function(
  File "C:\aitools\ctrlora\venv\lib\site-packages\gradio\blocks.py", line 1340, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\aitools\ctrlora\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\aitools\ctrlora\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "C:\aitools\ctrlora\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "C:\aitools\ctrlora\venv\lib\site-packages\gradio\utils.py", line 759, in wrapper
    response = f(*args, **kwargs)
  File "C:\aitools\ctrlora\app\gradio_ctrlora.py", line 312, in process
    samples, intermediates = ddim_sampler.sample(ddim_steps, num_samples,
  File "C:\aitools\ctrlora\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\aitools\ctrlora\cldm\ddim_hacked.py", line 103, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "C:\aitools\ctrlora\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\aitools\ctrlora\cldm\ddim_hacked.py", line 163, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "C:\aitools\ctrlora\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\aitools\ctrlora\cldm\ddim_hacked.py", line 190, in p_sample_ddim
    model_t = self.model.apply_model(x, t, c)
  File "C:\aitools\ctrlora\cldm\cldm_ctrlora_inference.py", line 177, in apply_model
    eps = diffusion_model(x=x_noisy, timesteps=t, context=cond_txt, control=control, only_mid_control=self.only_mid_control)
  File "C:\aitools\ctrlora\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\aitools\ctrlora\cldm\cldm.py", line 41, in forward
    h = torch.cat([h, hs.pop() + control.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 19 for tensor number 1 in the list.

```

pip list

```
(venv) C:\aitools\ctrlora>pip list
Package                   Version
------------------------- ------------------
absl-py                   2.1.0
accelerate                0.29.3
addict                    2.4.0
aiofiles                  23.2.1
aiohappyeyeballs          2.4.3
aiohttp                   3.10.10
aiosignal                 1.3.1
altair                    5.4.1
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.6.2.post1
async-timeout             4.0.3
attrs                     24.2.0
av                        13.1.0
basicsr                   1.4.2
black                     24.10.0
certifi                   2024.8.30
charset-normalizer        3.4.0
click                     8.1.7
cloudpickle               3.1.0
colorama                  0.4.6
coloredlogs               15.0.1
contourpy                 1.3.0
cycler                    0.12.1
detectron2                0.6
einops                    0.7.0
exceptiongroup            1.2.2
fastapi                   0.112.4
ffmpy                     0.4.0
filelock                  3.16.1
flatbuffers               24.3.25
fonttools                 4.54.1
frozenlist                1.4.1
fsspec                    2024.9.0
ftfy                      6.3.0
future                    1.0.0
fvcore                    0.1.5.post20221221
gradio                    4.27.0
gradio_client             0.15.1
grpcio                    1.66.2
h11                       0.14.0
httpcore                  1.0.6
httpx                     0.27.2
huggingface-hub           0.25.2
humanfriendly             10.0
hydra-core                1.3.2
idna                      3.10
imageio                   2.34.1
imageio-ffmpeg            0.4.9
importlib_metadata        8.5.0
importlib_resources       6.4.5
invisible-watermark       0.1.5
iopath                    0.1.9
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2024.10.1
kiwisolver                1.4.7
kornia                    0.7.2
kornia_rs                 0.1.5
lazy_loader               0.4
lightning-utilities       0.11.7
lmdb                      1.5.1
lpips                     0.1.4
Markdown                  3.7
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.2
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.1.0
mypy-extensions           1.0.0
narwhals                  1.9.3
networkx                  3.4.1
ninja                     1.11.1.1
numpy                     1.26.4
omegaconf                 2.3.0
onnx                      1.17.0
onnxruntime               1.19.2
open-clip-torch           2.24.0
opencv-contrib-python     4.9.0.80
opencv-python             4.9.0.80
opencv-python-headless    4.10.0.84
orjson                    3.10.7
packaging                 24.1
pandas                    2.2.3
pathspec                  0.12.1
pillow                    10.4.0
pip                       22.2.1
platformdirs              4.3.6
portalocker               2.10.1
prettytable               3.6.0
propcache                 0.2.0
protobuf                  5.28.2
psutil                    6.0.0
pycocotools               2.0.7
pydantic                  2.8.2
pydantic_core             2.20.1
pyDeprecate               0.3.1
pydub                     0.25.1
Pygments                  2.18.0
pyparsing                 3.2.0
pyreadline3               3.5.4
python-dateutil           2.9.0.post0
python-multipart          0.0.12
pytorch-lightning         1.5.0
pytz                      2024.2
PyWavelets                1.7.0
pywin32                   308
PyYAML                    6.0.2
referencing               0.35.1
regex                     2024.9.11
requests                  2.32.3
rich                      13.9.2
rpds-py                   0.20.0
ruff                      0.6.9
safetensors               0.4.5
scikit-image              0.24.0
scikit-learn              1.4.2
scipy                     1.14.1
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                63.2.0
shellingham               1.5.4
six                       1.16.0
sniffio                   1.3.1
starlette                 0.38.6
sympy                     1.13.3
tabulate                  0.9.0
tb-nightly                2.19.0a20241014
tensorboard               2.18.0
tensorboard-data-server   0.7.2
termcolor                 2.5.0
threadpoolctl             3.5.0
tifffile                  2024.9.20
timm                      0.9.16
tokenizers                0.12.1
tomli                     2.0.2
tomlkit                   0.12.0
torch                     1.13.1+cu117
torchaudio                0.13.1+cu117
torchmetrics              1.3.2
torchvision               0.14.1+cu117
tqdm                      4.66.5
transformers              4.19.2
typer                     0.12.5
typing_extensions         4.12.2
tzdata                    2024.2
urllib3                   2.2.3
uvicorn                   0.31.1
wcwidth                   0.2.13
websockets                11.0.3
Werkzeug                  3.0.4
wheel                     0.44.0
yacs                      0.1.8
yapf                      0.40.2
yarl                      1.15.2
zipp                      3.20.2

```

**Comment by 523997931** [comment]
hello the same issue, did you fix it?

**Comment by crjxixixi** [comment]
hello the same issue, did you fix it?

**Comment by MinGiSa** [comment]
try to resize input images.
for example, 256*256, 512*512.
image may requires divide by 64.
