### ISSUE TITLE
Training test!

### ISSUE THREAD

**Issue by toyxyz** [xyfJASON/ctrlora#9]
I prepared 1000 images and ran a training test. I set the max steps to 1000 and the training finished in 6 minutes, but the result is very cool!

Do you have any tips for running training? 

![image](https://github.com/user-attachments/assets/aa3ce5c1-8aa6-4343-8b03-248c54a09fcc)

![image](https://github.com/user-attachments/assets/2bee53d2-d481-4c76-936d-ed782bf81489)

**Comment by cchance27** [comment]
thats so cool!

**Comment by Jerry-155** [comment]
File "E:\CN\ctrlora\myenv\lib\site-packages\torch\distributed\distributed_c10d.py", line 886, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
Have you ever had that problem?

**Comment by Jerry-155** [comment]
Administrator@win-20231229PFV MINGW64 /e/CN/ctrlora
$ python scripts/train_ctrlora_finetune.py \
    --dataroot ./data/shoes \
    --config ./configs/ctrlora_finetune_sd15_rank128.yaml \
    --sd_ckpt ./ckpts/sd15/v1-5-pruned.ckpt \
    --cn_ckpt ./ckpts/ctrlora-basecn/ctrlora_sd15_basecn700k.ckpt \
    --name shoes1 \
    --max_steps 5000
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:118: UserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn("You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.")
E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:280: LightningDeprecationWarning: Base `LightningModule.on_train_batch_start` hook signature has changed in v1.5. The `dataloader_idx` argument will be removed in v1.7.
  rank_zero_deprecation(
initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:50388 (system error: 10049 - ▒▒▒▒▒▒▒▒▒▒▒У▒▒▒▒▒▒▒ĵ▒ַ▒▒Ч▒▒).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:50388 (system error: 10049 - ▒▒▒▒▒▒▒▒▒▒▒У▒▒▒▒▒▒▒ĵ▒ַ▒▒Ч▒▒).
logging improved.
Dataset size: 1163
Number of devices: 1
Batch size per device: 1
Gradient accumulation: 1
Total batch size: 1
No module 'xformers'. Proceeding without it.
ControlFinetuneLDM: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loaded model config from [./configs/ctrlora_finetune_sd15_rank128.yaml]
Loaded state_dict from [./ckpts/sd15/v1-5-pruned.ckpt]
Loaded state_dict from [./ckpts/ctrlora-basecn/ctrlora_sd15_basecn700k.ckpt]
Successfully initialize SD from ./ckpts/sd15/v1-5-pruned.ckpt
Successfully initialize ControlNet from ./ckpts/ctrlora-basecn/ctrlora_sd15_basecn700k.ckpt
Traceback (most recent call last):
  File "E:\CN\ctrlora\scripts\train_ctrlora_finetune.py", line 129, in <module>
    trainer.fit(model, dataloader)
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 735, in fit
    self._call_and_handle_interrupt(
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 770, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1131, in _run
    self.accelerator.setup_environment()
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\accelerators\gpu.py", line 39, in setup_environment
    super().setup_environment()
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 83, in setup_environment
    self.training_type_plugin.setup_environment()
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\plugins\training_type\ddp.py", line 192, in setup_environment
    self.setup_distributed()
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\plugins\training_type\ddp.py", line 279, in setup_distributed
    init_dist_connection(self.cluster_environment, self.torch_distributed_backend)
  File "E:\CN\ctrlora\myenv\lib\site-packages\pytorch_lightning\utilities\distributed.py", line 386, in init_dist_connection
    torch.distributed.init_process_group(
  File "E:\CN\ctrlora\myenv\lib\site-packages\torch\distributed\distributed_c10d.py", line 761, in init_process_group
    default_pg = _new_process_group_helper(
  File "E:\CN\ctrlora\myenv\lib\site-packages\torch\distributed\distributed_c10d.py", line 886, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in

**Comment by toyxyz** [comment]
> File "E:\CN\ctrlora\myenv\lib\site-packages\torch\distributed\distributed_c10d.py", line 886, in _new_process_group_helper raise RuntimeError("Distributed package doesn't have NCCL " "built in") RuntimeError: Distributed package doesn't have NCCL built in Have you ever had that problem?

I solved the problem with this method. 
https://github.com/xyfJASON/ctrlora/issues/8

**Comment by Jerry-155** [comment]
> > File "E:\CN\ctrlora\myenv\lib\site-packages\torch\distributed\distributed_c10d.py", line 886, in _new_process_group_helper raise RuntimeError("Distributed package doesn't have NCCL " "built in") RuntimeError: Distributed package doesn't have NCCL built in Have you ever had that problem?文件“E:\CN\ctrlora\myenv\lib\site-packages\torch\distributed\distributed_c10d.py”，第 886 行，在 _new_process_group_helper 中引发运行时错误（“分布式包没有 NCCL ”“内置”）运行时错误：分布式包没有内置 NCCL 您遇到过这个问题吗？
> 
> I solved the problem with this method.我用这个方法解决了这个问题。 #8

Thanks I figured out how to fix it, just need to delete the 
 strategy='ddp', that's it!

**Comment by Jerry-155** [comment]
What NVIDIA graphics card did you train on?

**Comment by toyxyz** [comment]
> What NVIDIA graphics card did you train on?

I used rtx 4090

**Comment by Jerry-155** [comment]
> > What NVIDIA graphics card did you train on?
> 
> I used rtx 4090

I'm 4080. I can't train.

**Comment by toyxyz** [comment]
I trained using 1000 hand-drawn images. It's a little fuzzy because the lines aren't consistent, but it works.

![image](https://github.com/user-attachments/assets/910fdf5c-be92-45ca-8ddc-0a373768bdf7)

**Comment by toyxyz** [comment]
> > > What NVIDIA graphics card did you train on?
> > 
> > 
> > I used rtx 4090
> 
> I'm 4080. I can't train.
VRAM usage is not that high, 16GB should work.

**Comment by Jerry-155** [comment]
You've got a great training set，from china?I want to train models that recognise different product materials and then optimise the light and shadow of the product based on the materials

**Comment by toyxyz** [comment]
> You've got a great training set，from china?I want to train models that recognise different product materials and then optimise the light and shadow of the product based on the materials

You can create datasets using texture images and 3D models that use those textures.

**Comment by crapthings** [comment]
@toyxyz how to get 3d pose like this

<img width="155" alt="image" src="https://github.com/user-attachments/assets/f75c12de-efef-4a01-9b6f-4ce5d7496160">

**Comment by toyxyz** [comment]
> @toyxyz how to get 3d pose like this
> 
> <img alt="image" width="155" src="https://private-user-images.githubusercontent.com/1147704/379829121-f75c12de-efef-4a01-9b6f-4ce5d7496160.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3OTI5MDgsIm5iZiI6MTcyOTc5MjYwOCwicGF0aCI6Ii8xMTQ3NzA0LzM3OTgyOTEyMS1mNzVjMTJkZS1lZmVmLTRhMDEtOWI2Zi00Y2U1ZDc0OTYxNjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTc1NjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDE1ZTU0NjRlZWI0YzYzMmFkOGYxZTNmNzYyZWU3ZmU1MzZkMTc2NjdjOWRlMThmMGVjYjJiMTMwY2M5Mzg2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.etI2iWPYRE6g5EyCRh2RfqUsbp980BzTvAocWJLJnSs">

Rendered using blender.

**Comment by LynnHo** [comment]
> I trained using 1000 hand-drawn images. It's a little fuzzy because the lines aren't consistent, but it works.
> 
> ![image](https://private-user-images.githubusercontent.com/8006000/378321786-910fdf5c-be92-45ca-8ddc-0a373768bdf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDUzMjAsIm5iZiI6MTcyOTg0NTAyMCwicGF0aCI6Ii84MDA2MDAwLzM3ODMyMTc4Ni05MTBmZGY1Yy1iZTkyLTQ1Y2EtOGRkYy0wYTM3Mzc2OGJkZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMDgzMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYzNTYzNmQwOWMyZDg0MGY0M2Y4NmNkZDY3OTc2ZjIyNmI3ZTFmNTZlOTNlM2MwZjBmZWNhMDRmNDgzNzFhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nyd5bDRSKJyGA1ZM29J7HfoXwblCb35q1V_12ifIifs)

Hi, many thanks for your testing!!! By the way, how do you collect this kind of data?

**Comment by toyxyz** [comment]
> > I trained using 1000 hand-drawn images. It's a little fuzzy because the lines aren't consistent, but it works.
> > ![image](https://private-user-images.githubusercontent.com/8006000/378321786-910fdf5c-be92-45ca-8ddc-0a373768bdf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NDUzMjAsIm5iZiI6MTcyOTg0NTAyMCwicGF0aCI6Ii84MDA2MDAwLzM3ODMyMTc4Ni05MTBmZGY1Yy1iZTkyLTQ1Y2EtOGRkYy0wYTM3Mzc2OGJkZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjVUMDgzMDIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmYzNTYzNmQwOWMyZDg0MGY0M2Y4NmNkZDY3OTc2ZjIyNmI3ZTFmNTZlOTNlM2MwZjBmZWNhMDRmNDgzNzFhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.nyd5bDRSKJyGA1ZM29J7HfoXwblCb35q1V_12ifIifs)
> 
> @toyxyz Hi, many thanks for your testing!!! By the way, how do you collect this kind of data?

I drew it myself, of course!

**Comment by ccnguyen** [comment]
@toyxyz Great work!! Did you use all the default settings to train these? I've been trying myself with a dataset of 1000 rough lineart to art pairs and the following command but it does not seem to be learning anything....
```
python scripts/train_ctrlora_finetune.py \
    --dataroot ./data/dataset \
    --config ./configs/ctrlora_finetune_sd15_rank128.yaml \
    --sd_ckpt ./ckpts/sd15/v1-5-pruned.ckpt \
    --cn_ckpt ./ckpts/control_sd15_init.pth \
    --name lineart_custom \
    --bs 1 \
    --img_logger_freq 2000 \
    --ckpt_logger_freq 2000
````

**Comment by LynnHo** [comment]
> @toyxyz Great work!! Did you use all the default settings to train these? I've been trying myself with a dataset of 1000 rough lineart to art pairs and the following command but it does not seem to be learning anything....
> 
> ```
> python scripts/train_ctrlora_finetune.py \
>     --dataroot ./data/dataset \
>     --config ./configs/ctrlora_finetune_sd15_rank128.yaml \
>     --sd_ckpt ./ckpts/sd15/v1-5-pruned.ckpt \
>     --cn_ckpt ./ckpts/control_sd15_init.pth \
>     --name lineart_custom \
>     --bs 1 \
>     --img_logger_freq 2000 \
>     --ckpt_logger_freq 2000
> ```

@ccnguyen  you need command like
```
python scripts/train_ctrlora_finetune.py \
  --dataroot ./data/dataset  \
  --config ./configs/ctrlora_finetune_sd15_rank128.yaml \
  --sd_ckpt ./ckpts/sd15/v1-5-pruned.ckpt \
  --cn_ckpt ./ckpts/ctrlora-basecn/ctrlora_sd15_basecn700k.ckpt \
  --max_steps 1000
```
